"""followers

Revision ID: 13425a3d543b
Revises: 220ab0cdbb64
Create Date: 2025-04-22 17:20:49.419835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13425a3d543b'
down_revision = '220ab0cdbb64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
